# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadModel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loadModelUI(object):
    def setupUi(self, loadModelUI):
        loadModelUI.setObjectName("loadModelUI")
        loadModelUI.resize(392, 277)
        self.label = QtWidgets.QLabel(loadModelUI)
        self.label.setGeometry(QtCore.QRect(80, 10, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(loadModelUI)
        self.pushButton.setGeometry(QtCore.QRect(140, 220, 131, 61))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(loadModelUI)
        self.label_2.setGeometry(QtCore.QRect(90, 190, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(loadModelUI)
        self.progressBar.setGeometry(QtCore.QRect(50, 130, 331, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(loadModelUI)
        self.pushButton.clicked.connect(loadModelUI.close)
        QtCore.QMetaObject.connectSlotsByName(loadModelUI)

    def retranslateUi(self, loadModelUI):
        _translate = QtCore.QCoreApplication.translate
        loadModelUI.setWindowTitle(_translate("loadModelUI", "Form"))
        self.label.setText(_translate("loadModelUI", "Load Model"))
        self.pushButton.setText(_translate("loadModelUI", "Choose Model"))
        self.label_2.setText(_translate("loadModelUI", "Please click to load model"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loadModelUI = QtWidgets.QWidget()
    ui = Ui_loadModelUI()
    ui.setupUi(loadModelUI)
    loadModelUI.show()
    sys.exit(app.exec_())
